string light_name                    # name of Gazebo Light
---
std_msgs/ColorRGBA diffuse           # diffuse color as red, green, blue, alpha
float64 attenuation_constant
float64 attenuation_linear
float64 attenuation_quadratic
bool success                         # return true if get successful
string status_message                # comments if available
