---
float64 sim_time                     # current sim time
string[] model_names                 # list of models in the world
bool rendering_enabled               # If gazebo rendering engine is enabled, currently always True
bool success                         # return true if get successful
string status_message                # comments if available
