---
float64 sim_time                     # current sim time
string[] model_names                 # list of models in the world
bool rendering_enabled               # if X is used
bool success                         # return true if get successful
string status_message                # comments if available
