#!/bin/sh
#
# @name Plane SITL with gimbal
#

. ${R}etc/init.d-posix/airframes/1030_plane

if [ $AUTOCNF = yes ]
then
	param set TRIG_INTERFACE 3
	param set TRIG_MODE 4
	param set MNT_MODE_IN 4
	param set MNT_MODE_OUT 2
	param set MAV_PROTO_VER 2
fi