# object name to be registered
string name

---

# succes flag
byte success

# successfully registered
byte SUCCESS=0

# object already registered
byte EXISTS=1

# could not query required information for this object
byte ERROR_INFO=2
